<?php

namespace PrincipalBundle\Repository;

/**
 * AliasesDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasesDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
