<?php

namespace PrincipalBundle\Repository;

/**
 * AliasesNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasesNameRepository extends \Doctrine\ORM\EntityRepository
{
}
