<?php

namespace PrincipalBundle\Repository;

/**
 * RedirecmodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirecmodeRepository extends \Doctrine\ORM\EntityRepository
{
}
