<?php

namespace PrincipalBundle\Repository;

/**
 * TxtipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TxtipRepository extends \Doctrine\ORM\EntityRepository
{
}
