<?php

namespace PrincipalBundle\Repository;

/**
 * UserAdministratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAdministratorRepository extends \Doctrine\ORM\EntityRepository
{
}
